<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.flamehub</groupId>
    <artifactId>flamehub-recode</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>afk-zone</module>
        <module>ranking</module>
        <module>commons</module>
        <module>commons-bukkit</module>
        <module>proxy-core</module>
        <module>time-played</module>
        <module>wallet</module>
        <module>lobby</module>
        <module>kits</module>
        <module>economy</module>
        <module>crates</module>
        <module>auctionhouse</module>
        <module>punishment</module>
        <module>scratch</module>
        <module>reward</module>
        <module>reward/reward-discord-bot</module>
        <module>reward/reward-api</module>
        <module>reward/reward-bukkit</module>
        <module>code</module>
        <module>check-system</module>
        <module>shulker</module>
        <module>player-sync</module>
        <module>mines</module>
        <module>daily-reward</module>
        <module>achievements</module>
        <module>wallet-api</module>
        <module>essentials</module>
    </modules>

    <build>
        <finalName>flamehub-${project.artifactId}</finalName>
    </build>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>eternalcodeReposiliteReleases</id>
            <url>https://repo.eternalcode.pl/releases</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>okaeri-repo</id>
            <url>https://storehouse.okaeri.eu/repository/maven-public/</url>
        </repository>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
            <layout>default</layout>
        </repository>

        <repository>
            <id>panda-repo</id>
            <url>https://repo.panda-lang.org/releases</url>
        </repository>
    </repositories>


</project>