<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>proxy-core</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.8.1</version>
      </plugin>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.5.0</version>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <artifactId>velocity-api</artifactId>
      <groupId>com.velocitypowered</groupId>
      <scope>provided</scope>
      <version>3.4.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>commons</artifactId>
      <groupId>io.github.flamehub.commons</groupId>
      <scope>compile</scope>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>litecommands-velocity</artifactId>
      <groupId>dev.rollczi</groupId>
      <scope>compile</scope>
      <version>3.9.7</version>
    </dependency>
    <dependency>
      <artifactId>okhttp</artifactId>
      <groupId>com.squareup.okhttp</groupId>
      <version>2.7.5</version>
    </dependency>
    <dependency>
      <artifactId>okaeri-sdk</artifactId>
      <groupId>eu.okaeri</groupId>
      <version>1.4.5</version>
    </dependency>
  </dependencies>
  <groupId>io.github.flamehub.proxy.core</groupId>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>flamehub-recode</artifactId>
    <groupId>io.github.flamehub</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <repositories>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
    <repository>
      <id>sonatype-snapshots</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
  </repositories>

</project>