<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>mines</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.8.1</version>
      </plugin>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.5.0</version>
      </plugin>
    </plugins>
  </build>

  <dependencies>

    <dependency>
      <artifactId>commons-bukkit</artifactId>
      <groupId>io.github.flamehub.commons.bukkit</groupId>
      <scope>provided</scope>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>paper-api</artifactId>
      <groupId>io.papermc.paper</groupId>
      <scope>provided</scope>
      <version>1.20.2-R0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>placeholderapi</artifactId>
      <groupId>me.clip</groupId>
      <scope>provided</scope>
      <version>2.11.6</version>
    </dependency>
    <dependency>
      <artifactId>worldedit-bukkit</artifactId>
      <groupId>com.sk89q.worldedit</groupId>
      <scope>provided</scope>
      <version>7.2.18</version>
    </dependency>
    <dependency>
      <artifactId>decentholograms</artifactId>
      <groupId>com.github.decentsoftware-eu</groupId>
      <scope>provided</scope>
      <version>2.8.5</version>
    </dependency>
  </dependencies>
  <groupId>io.github.flamehub.mines</groupId>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>flamehub-recode</artifactId>
    <groupId>io.github.flamehub</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
    <repository>
      <id>placeholderapi</id>
      <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
    </repository>

    <repository>
      <id>enginehub-maven</id>
      <url>https://maven.enginehub.org/repo/</url>
    </repository>
  </repositories>

</project>