mongo.uri = mongodb://admin:FGZtTvywHqQ5MWY9t2KhahqSh8ACVFpRH9TnmVyhSuxSBBTxPH@85.10.196.21:10001
redis.host = 85.10.196.21
redis.port = 10000
redis.password = hBCrmERhtnh3JQd94rF935E4Pn2mXC8Jt8bgeGa2fmTWAw8qwa