<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>commons-bukkit</artifactId>
  <build>
    <defaultGoal>clean install</defaultGoal>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.8.1</version>
      </plugin>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.6.0</version>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <artifactId>api</artifactId>
      <groupId>net.luckperms</groupId>
      <scope>provided</scope>
      <version>5.4</version>
    </dependency>
    <dependency>
      <artifactId>spigot</artifactId>
      <groupId>com.github.retrooper.packetevents</groupId>
      <scope>provided</scope>
      <version>2.2.0</version>
    </dependency>
    <dependency>
      <artifactId>item-nbt-api-plugin</artifactId>
      <groupId>de.tr7zw</groupId>
      <scope>compile</scope>
      <version>2.12.4</version>
    </dependency>
    <dependency>
      <artifactId>commons</artifactId>
      <groupId>io.github.flamehub.commons</groupId>
      <scope>compile</scope>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>paper-api</artifactId>
      <groupId>io.papermc.paper</groupId>
      <scope>provided</scope>
      <version>1.20.4-R0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>spigot</artifactId>
      <groupId>org.spigotmc</groupId>
      <scope>provided</scope>
      <version>1.20.4-R0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>placeholderapi</artifactId>
      <groupId>me.clip</groupId>
      <scope>provided</scope>
      <version>2.11.6</version>
    </dependency>
    <dependency>
      <artifactId>litecommands-bukkit</artifactId>
      <groupId>dev.rollczi</groupId>
      <scope>compile</scope>
      <version>3.9.7</version>
    </dependency>
    <dependency>
      <artifactId>fastboard</artifactId>
      <groupId>fr.mrmicky</groupId>
      <scope>compile</scope>
      <version>2.1.2</version>
    </dependency>
    <dependency>
      <artifactId>triumph-gui</artifactId>
      <groupId>dev.triumphteam</groupId>
      <scope>compile</scope>
      <version>3.1.5</version>
    </dependency>
    <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson</artifactId>
      <version>3.45.1</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <groupId>io.github.flamehub.commons.bukkit</groupId>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>flamehub-recode</artifactId>
    <groupId>io.github.flamehub</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>


</project>